name: scrape-npb-schedule

on:
  schedule:
    - cron: 0 19 * * *
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "**/*.ts"
      - ".github/workflows/**"

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Build
        run: npx tsc

      - name: Scrape
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: node dist/index.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --staged --quiet || (git commit -m "update npb schedule on $(TZ='Asia/Tokyo' date '+%Y-%m-%d')" && git push)
